name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Dandraka.XmlUtilities/Dandraka.XmlUtilities.sln
    - name: Build
      run: dotnet build Dandraka.XmlUtilities/Dandraka.XmlUtilities.sln --no-restore
    - name: Test
      run: dotnet test Dandraka.XmlUtilities/Dandraka.XmlUtilities.Tests/Dandraka.XmlUtilities.Tests.csproj --no-build --verbosity normal
